[package]
name = "wwhd-trainer"
version = "0.5.0"
edition = "2021"
authors = ["29th-Day"]
license = "GPL3"

[dependencies]
wut = { path = "../wut", version = "*" }
wups = { path = "../wups", version = "*" }
overlay = { path = "../overlay", version = "*" }
notifications = { path = "../notifications", version = "*" }
