[package]
name = "wwhd-trainer"
version = "0.5.0"
edition = "2021"
authors = ["29th-Day"]
license = "GPL3"

[dependencies]
wut = { git = "https://github.com/rust-wiiu/wut" }
wups = { git = "https://github.com/rust-wiiu/wups" }
overlay = { git = "https://github.com/rust-wiiu/overlay" }
notifications = { git = "https://github.com/rust-wiiu/notifications" }
