extend = [
    { path = "target/cargo-make/Makefile.toml" },
]

[config]
load_script = """[ -d "./target/cargo-make" ] || git clone https://github.com/rust-wiiu/Makefile.git ./target/cargo-make"""

[tasks.build]
clear = true
dependencies = ["wups"]

[tasks.run]
clear = true
dependencies = ["upload-wiiload"]

[tasks.upload-wiiload]
command = "wiiload"
args = ["${OUT_FILE}"]
dependencies = ["wups"]
